<?php namespace WPKG\Drivers;

use WPKG\Drivers\XML\Errors;
use WPKG\Interfaces\Import;

class XMLImport implements Import
{
    use Errors;

    /**
     * @var
     */
    private $_xml;

    /**
     * Convert XML to array
     *
     * @param   string $data - XML in plain text format
     * @return  mixed
     */
    public function import($data)
    {
        // Load XML from string
        $this->_xml = simplexml_load_string($data);

        // Convert from creepy object to normal array
        $array = json_decode(json_encode((array)$this->_xml), true);

        // Run parser
        return $this->parse($array);
    }

    /**
     * Convert array generated by SimpleXML to WPKG object
     *
     * @param   array $array
     * @return  bool
     */
    private function parse(array $array)
    {
        $out = false;
        foreach ($array as $key => $value) {
            // Ignore comments in XML
            if ('comment' == strtolower($key)) continue;

            // Choose the driver's mode for work
            $prefix = '\\WPKG\\Drivers\\XML\\';
            $class = $prefix . ucfirst("${key}s");
            $class = new $class();

            // Import values
            $out = $class->import($value);
        }
        return $out;
    }
}