<?php namespace WPKG\Drivers;

use WPKG\Interfaces\Import;

class XMLImport implements Import
{
    /**
     * Convert XML to array
     *
     * @param   string $data - XML in plain text format
     * @return  mixed
     */
    public function import($data)
    {
        // Load XML from string
        $xml = new \SimpleXMLElement($data);

        // Convert from creepy object to normal array
        $array = json_decode(json_encode((array)$xml), true);

        // Run parser
        return $this->parse($array);
    }

    /**
     * Convert array generated by SimpleXML to WPKG object
     *
     * @param   array $array
     * @return  mixed
     */
    private function parse(array $array)
    {
        $out = false;

        // If we have some parameters inside, then need to work on config
        if (isset($array['param'])) {
            $class = new \WPKG\Drivers\XML\Config();
            return $class->import($array);
        }

        // Parse array in any other case
        foreach ($array as $key => $value) {
            // Ignore comments in XML
            if ('comment' == strtolower($key)) continue;

            // Choose the driver's mode for work
            $prefix = '\\WPKG\\Drivers\\XML\\';
            $class = $prefix . ucfirst("${key}s");
            $class = new $class();

            // Import values
            $out = $class->import($value);
        }
        return $out;
    }
}